# Generated by Django 6.0.6 on 2026-06-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated if left blank.', unique=True)),
                ('subtitle', models.CharField(help_text='A short punchy description for the preview card.', max_length=250)),
                ('description', models.TextField(help_text='Detailed description of the project, challenges, and solutions.')),
                ('technologies', models.CharField(help_text='Comma-separated skills (e.g., Django, Tailwind, MySQL, JS)', max_length=500)),
                ('image', models.ImageField(help_text='Main project screenshot', upload_to='projects/')),
                ('github_url', models.URLField(blank=True, max_length=300, null=True)),
                ('live_url', models.URLField(blank=True, max_length=300, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text="Check this if it's your flagship project (like the Client Store) to change its layout.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
