# Generated by Django 6.0.6 on 2026-06-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mobile_description',
            field=models.TextField(blank=True, help_text='A concise version of the description for mobile view.', null=True),
        ),
    ]
