# Generated by Django 6.0.6 on 2026-06-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_mobile_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='mobile_description',
            new_name='mobile_desc',
        ),
    ]
